### ISSUE TITLE
在PS-2461-7H中不起作用

### ISSUE THREAD

**Issue by Xing-Fax** [hitsword/csps_esphome#1]
它在PS-2461-7H工作时无法读取到正确的数值，数值误差非常大并且在不断的改变，我猜是因为错误的地址导致，此外，风扇转速以及调节转速可以正常的显示和修改。

**Comment by nowfuture4** [comment]
华为pac3000s12t1能够按照手册修改吗？
<img width="547" alt="hw_pac3000s12t1 2023-10-10 113011" src="https://github.com/hitsword/csps_esphome/assets/50253917/9fd74cac-547b-4425-a61a-d8d83c808c90">

**Comment by hitsword** [comment]
> 它在PS-2461-7H工作时无法读取到正确的数值，数值误差非常大并且在不断的改变，我猜是因为错误的地址导致，此外，风扇转速以及调节转速可以正常的显示和修改。

PMBUS增加上拉电阻，上拉至5v，这不是地址错误。光宝的CSPS电源不加上拉电阻这个问题特别明显，台达产的稍微好一些。

**Comment by hitsword** [comment]
> 华为pac3000s12t1能够按照手册修改吗？ <img alt="hw_pac3000s12t1 2023-10-10 113011" width="547" src="https://user-images.githubusercontent.com/50253917/273767986-9fd74cac-547b-4425-a61a-d8d83c808c90.png">

你自己尝试，PMBUS部分的代码是我引用别人写的类库。

**Comment by BG8HQE** [comment]
华为EPW750-12A扫描到两个I2C地址：[16:13:49][I][i2c.arduino:102]: Found i2c device at address 0x57
[16:13:49][I][i2c.arduino:102]: Found i2c device at address 0x5F，不能读数，这个是不是修改地址地方，修改了还是不能读到：CSPS PowerSupply(0x57, 0x5F, true);
